imports:
    - { resource: imgPusher/ }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $imgResizerConfig: '%imgResizer%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Imagine\Gd\Imagine: ~
    Spatie\Dropbox\Client: ~
    Symfony\Component\Filesystem\Filesystem: ~
